[package]
name = "mcp-gateway"
version = "0.2.0"
edition = "2024"

[dependencies]
mcp-runner = "0.3.1"
tokio = { version = "1.45.0", features = ["full", "signal"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
getch = "0.3.1"
